name: Run Maigret OSINT Scan (Fast)

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'The username to search for'
        required: true

jobs:
  osint_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' # Caches the installation for subsequent runs

    - name: Install Maigret
      run: pip install maigret

    - name: Run Maigret Scan
      run: maigret ${{ github.event.inputs.username }} -a
